### ISSUE TITLE
Copy Selected Bone Weights Copies Unselected Bones

### ISSUE THREAD

**Issue by AdamVezina** [ousnius/BodySlide-and-Outfit-Studio#369] opened 2021-07-18 03:45 UTC
Issue: When shift-clicking multiple bones in the list and then choosing to copy selected bone weights from the Shape menu, other bones that were not selected in the list are copied as well.

Exact steps to reproduce:

1. Load an armor that has weighting for the NPC Head [Head] bone.
2. Select a single shape that has weighting for the NPC Head [Head] bone in the Meshes tab.
2. Move to the Bones tab
3. Shift-click to select all bones under the NPC Head [Head] bone.
4. Go to Shape > Copy Selected Weights
5. Click OK to accept the defaults
6. Go back to your armor, you'll see the weighting for the NPC Head [Head] bone has changed on the selected shape, even though the bone wasn't selected.

**Comment by ousnius** [comment] 2021-07-18 18:39
@AdamVezina This isn't caused by the program copying weights to bones that aren't selected - it's an intentional side effect caused by weight normalization. When any weight on a specific area is changing, the other weights (on other bones) need to adjust accordingly.

See https://github.com/ousnius/BodySlide-and-Outfit-Studio/wiki/Weight-Normalization

**Comment by ousnius** [comment] 2022-01-22 21:57
@AdamVezina Closing this for now. If you have more details on what exactly is going wrong or is confusing, feel free to post.

**Closed as completed by ousnius** 2022-01-22 21:57 UTC
