### ISSUE TITLE
Sub-segment assignment loss when painting sub-segments.

### ISSUE THREAD

**Issue by Evan555alpha** [ousnius/BodySlide-and-Outfit-Studio#329] opened 2020-12-11 14:22 UTC
**Description**
For Fallout 4, I have an armour-piece outfit that I have been creating for a while now. I have been creating the sub-segment data through Outfit Studio v5.2.0.0. I have run into a scenario where, upon painting the last few faces on the last sub-segment I am trying to create, all sub-segment assignments are subsequently cleared.
All sub-segments remain in the top right window, but each sub-segment's assigned faces becomes blank, and I have to start over from whenever the project was last saved.
The expected behaviour is for that to, well, not happen.

**How to reproduce**
1. Have outfit that has no sub-segments.
2. Hand-assign sub-segments. In my case it's segments 0 through 6, and then sub-segments 0 through 4 for both segments 5 and 6, for the legs.
3. Have an area like so, where there's three sub-segments; one that is painted the way you want, one that you are painting over, and one that you are trying to paint. In my case, I had already properly assigned all other sub-segments the way I wanted. This was the last little bit that I needed to do.
![image](https://user-images.githubusercontent.com/10338511/101914088-f35ffa80-3c17-11eb-8600-2ede6ff7c8b7.png)

4. Attempt to paint the last of the final sub-segment. Upon doing so, the neighbouring sub-segment will become a slightly different colour. This indicates that sub-segment assignment is about to be lost.
![image](https://user-images.githubusercontent.com/10338511/101914194-17bbd700-3c18-11eb-95c7-702ce3acecea.png)
![image](https://user-images.githubusercontent.com/10338511/101914228-24402f80-3c18-11eb-952b-3e0aaa0a4109.png)

5. Hit "Apply" in the top right. All sub-segment assignments will be lost. If one does not save after this happens, one can reload the project to go back to what the sub-segment assignments were at the time of last saving.
![image](https://user-images.githubusercontent.com/10338511/101914256-2dc99780-3c18-11eb-9975-649370677f0f.png)

If needed, I can provide the project file(s) these images were taken from, in the event that it's something wrong with the project itself.

**Comment by ousnius** [comment] 2020-12-11 17:12
@Evan555alpha I've played around with it a bit and this seems to happen when you right-click the top segment (not sub segment) to insert the new sub segments via the context menu. The internal IDs get shuffled the wrong way.

If you always right-click the newly added sub segment to add the next sub segment (instead of the parent segment), then it will work. I will think of what to do to fix it.

**Comment by ousnius** [comment] 2020-12-11 19:37
This should be fixed for the next version, thanks for the report.

**Closed as completed by ousnius** 2020-12-11 19:37 UTC
Labels: bug

**Comment by sts1skj** [comment] 2022-02-19 07:49
@Evan555alpha I was unable to reproduce your bug by trying to follow your instructions, but I was able to trigger it.  The key trigger was this: hitting apply while the last segment or subsegment was empty.  (By empty, I mean it had no triangles assigned to it.)

Hopefully I have finally fixed this bug in https://github.com/ousnius/nifly/pull/26
